### ISSUE TITLE
AttributeError: '_Reactor' object has no attribute 'connectTCP'

### ISSUE THREAD

**Issue by klassegeljakt** [FredKSchott/CoVim#89]
When I attempt to start a server inside vim by typing:

    :CoVim start 22 "abc"

I get the error:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<string>", line 305, in command
      File "<string>", line 263, in createServer
      File "<string>", line 249, in initiate
    AttributeError: '_Reactor' object has no attribute 'connectTCP'

I use OSX 10.10.5 and have followed all installation instructions.

Also, when I try to connect I get this error:

    klass-air:plugin Klas$ python CoVimClient.vim 8555
      File "CoVimClient.vim", line 2
        if !has('python')
           ^
    SyntaxError: invalid syntax

What went wrong?

**Comment by klassegeljakt** [comment]
The first error seemed to get fixed by upgrading twisted and argparse. The second error was just a misunderstanding, the CoVimClient.vim file should not be launched from the command line.
