### ISSUE TITLE
Python exception when starting covim

### ISSUE THREAD

**Issue by alem0lars** [FredKSchott/CoVim#90]
I've started CoVim with the following command:
```
:CoVim start 1234 foo
```

Got the following error:

```
Connecting...
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "<string>", line 62, in dataReceived

  File "<string>", line 266, in setupWorkspace

  File "/usr/lib64/python2.7/site-packages/neovim/api/nvim.py", line 201, in command
    return self.request('vim_command', string, **kwargs)
  File "/usr/lib64/python2.7/site-packages/neovim/api/nvim.py", line 129, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 89, in request
    v = self._yielding_request(method, args)
  File "/usr/lib64/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 154, in _yielding_request
    return parent.switch()
exceptions.AttributeError: 'NoneType' object has no attribute 'switch'
```

**Comment by jgelens** [comment]
Got the same error, were you able to fix it ?

**Comment by alem0lars** [comment]
No..

**Comment by LunarArcanus** [comment]
@alem0lars Are you using NeoVim? Does the problem persist if you use regular vim?

**Comment by elliotec** [comment]
Same issue here in Neovim.

**Comment by Masterchef365** [comment]
@elliotec Same here. I've heard that twisted has problems in neovim?

**Comment by dj95** [comment]
Same here with neovim

**Comment by elliotec** [comment]
@Masterchef365 ¯\_(ツ)_/¯ I gave up and used floobits. I recommend it.

**Comment by Masterchef365** [comment]
@elliotec Did exactly the same thing, mostly after trying CoVim out on regular vim and having it bug out a little bit. I think it was in conflict with some other plugins...

**Comment by willwillsiii** [comment]
Seems like an issue with the twisted version. See this:
[http://stackoverflow.com/questions/42731760/attributeerror-module-object-has-no-attribute-op-no-tlsv1-1]

**Comment by alem0lars-yoroi** [comment]
Are there any updates on this issue?

I'm still having the same problem with NeoVim.
